# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
use_frameworks!
workspace 'Reciplease.xcworkspace'


target 'Application' do
  # Comment the next line if you don't want to use dynamic frameworks
 project 'Application/Application.xcodeproj'
  
  pod 'Alamofire', '5.0.0'
  # Pods for Application

end
